contracts:
  router:
    address: '0x0880cf17Bd263d3d3a5c09D2D86cCecA3CcbD97c'
    compiler_settings:
      compiler_version: 0.3.10
      evm_version: paris
      optimisation_level: GAS
    constructor_args_encoded: 000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
    contract_github_url: https://github.com/curvefi/curve-lite/blob/b51fe356ae83cb23d363f5d048b3e7d47215512f/contracts/helpers/router/router_v_110.vy
    contract_version: 1.1.0
    deployment_timestamp: 1721381817
